# Generated by Django 3.1 on 2020-08-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_drinks_updated_at'),
        ('carts', '0002_auto_20200812_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=None, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cart')),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='drinks.drinks')),
            ],
        ),
    ]
