# Generated by Django 3.1 on 2020-08-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cart',
        ),
        migrations.DeleteModel(
            name='PaymentRow',
        ),
    ]
