# Generated by Django 3.1 on 2020-08-11 10:01

from django.db import migrations, models
import drinks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.PositiveIntegerField(default=None)),
                ('desc', models.TextField(blank=True, max_length=1024, null=True)),
                ('food_images', models.ImageField(upload_to=drinks.models.get_image_filename, verbose_name='Image')),
                ('likes', models.PositiveIntegerField()),
            ],
        ),
    ]
