# Generated by Django 3.1 on 2020-08-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(max_length=512, null=True)),
                ('brand_img', models.ImageField(upload_to='drinks/{self.name}/')),
            ],
        ),
    ]
