# Generated by Django 3.1 on 2020-08-13 05:10

from django.db import migrations, models
import drinks.models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_img',
            field=models.ImageField(upload_to=drinks.models.get_brand_name),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(default='Anoymous', max_length=32, unique=True),
        ),
    ]
