# Generated by Django 3.1 on 2020-08-13 05:11

from django.db import migrations, models
import django.db.models.deletion
import drinks.models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20200813_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drinks.brand'),
        ),
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(null=True, upload_to=drinks.models.get_brand_name),
        ),
    ]
