# Generated by Django 3.1 on 2020-08-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
